import re
import json
import sys
import os
from datetime import datetime, timezone, timedelta

with open(sys.argv[1], 'r', encoding='utf-8') as file:
    descr = json.load(file)['ietf-sid-file:sid-file']['description']

match = re.match(r"Generated by pyang \d+\.\d+\.\d+ at (.*)", descr)
parsed_time = datetime.strptime(match.groups()[0], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
if abs(parsed_time - datetime.now(tz=timezone.utc)) < timedelta(seconds=30):
    cmd=f"sed -i 's/Generated by pyang .* at .*Z/pyang description/' {sys.argv[1]}"
    print(cmd)
    os.system(cmd)

