#!/bin/bash

# Defaults for arguments
schema=rng
target=get-reply
dir=input
name="_NO_NAME_"

xslt_dir=${XSLT_DIR:-.}
rng_lib=${RNG_LIBDIR:-.}/relaxng-lib.rng
usage() {
    cat <<EOF

Usage: yang2schema <options> <filename>

Generates validation schema from YANG module in <filename>.

Options:
  -h           Show this help message and exit
  -s <schema>  Select the schema to generate (default "rng").
               [NOTE: Only "rng" is currently supported.]
  -t <target>  Specify the validation target (default "get-reply").
               Must be one of "get-reply", "rpc" and "notif".
               Option -n <name> is required for the latter two.
  -n <name>    Specify the name of notification or RPC method.
               The name has to include the standard NS prefix.
  -i|-o        Specify RPC request (-i) or reply (-o) (default -i).
EOF
}

gen_relaxng() {
    pyang -f rng $yam | xsltproc --stringparam rng-lib $rng_lib \
	--stringparam schema $schema --stringparam target $target \
	--stringparam name $name --stringparam dir $dir \
	$xslt_dir/gen-relaxng.xsl -
}

while getopts ":hs:t:n:io" opt ; do
    case $opt in
	h)
	    usage
	    exit 0
	    ;;
	s)
	    schema=$OPTARG
	    ;;
	t)
	    target=$OPTARG
	    if [[ $target != "get-reply" && $target != "rpc" \
		&& $target != "notif" ]] ; then
		echo "Invalid argument for -t: $target."
		exit 1
	    fi
	    ;;
	n)
	    name=$OPTARG
	    ;;
	i)
	    dir=input
	    ;;
	o)
	    dir=output
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG." >&2
	    exit 1
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument."
	    ;;
    esac
done
shift $(($OPTIND-1))
yam=$1
if [[ ($target == "rpc" || $target == "notif") && $name == "_NO_NAME_" ]]
then
    echo "Requires $target name (option -n)." >&2
    exit 1
fi
if [[ $yam == "" ]] ; then
    echo "No input file given." >&2
    usage
    exit 1
fi
if [ ! -f $yam ] ; then
    echo "File '$yam' not found."
    exit 1
fi

case $schema in
    rng)
	gen_relaxng
	;;
    *)
	echo "Invalid argument for -s: $schema."
	exit 1
	;;
esac