'\" t
.\"     Title: yang2dsdl
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 18 March 2010
.\"    Manual: pyang manual
.\"    Source: pyang manual
.\"  Language: English
.\"
.TH "YANG2DSDL" "1" "18 March 2010" "pyang manual" "pyang manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
yang2dsdl \- translates YANG data models to DSDL schemas and validates instance documents\&.
.SH "SYNOPSIS"
.HP \w'\fByang2dsdl\fR\ 'u
\fByang2dsdl\fR [\-t\ \fItarget\fR] [\-d\ \fIdir\fR] [\-b\ \fIbasename\fR] [\-v\ \fIinstance\fR] \fImodule\fR...
.HP \w'\fByang2dsdl\fR\ 'u
\fByang2dsdl\fR \-h
.SH "DESCRIPTION"
.PP
This shell script facilitates the translation of a data model described by one or more input YANG modules to DSDL schemas (RELAX NG, Schematron and DSRL) for a selected instance XML document type\&. Optionally, an instance document of the given type can be immediately validated against the schemas\&.
.PP
The input module(s) can be expressed in YANG or YIN syntax\&. The output DSDL schemas are written to the directory
\fIdir\fR
(current directory by default)\&.
.PP
The output schemas are contained in five files with a common
\fIbasename\fR:
.PP
\fIbasename\fR\&.cts
.RS 4
Conceptual tree schema, an interim annotated RELAX NG schema\&. This schema cannot be used for direct validation\&.
.RE
.PP
\fIbasename\fR\&.rng
.RS 4
RELAX NG schema for the target document type\&.
.RE
.PP
\fIbasename\fR\-gdefs\&.cts
.RS 4
Auxiliary RELAX NG schema containing global named pattern definitions\&.
.RE
.PP
\fIbasename\fR\&.sch
.RS 4
Schematron schema for the target document type\&.
.RE
.PP
\fIbasename\fR\&.dsrl
.RS 4
DSRL schema for the target document type\&.
.RE
.PP
The
\fItarget\fR
parameter specifies the type of the target instance document\&. Supported values are:
.PP
dstore
.RS 4
Raw datastore contents without any encapsulating elements\&. If the input YANG modules define a data model with multiple root elements, the raw datastore may not be valid XML\&. In this case, the resulting DSDL schemas assume a choice of the top\-level root elements\&.
.RE
.PP
get\-reply
.RS 4
A complete NETCONF protocol data unit (PDU) containing a reply to the <get> operation\&.
.RE
.PP
getconf\-reply
.RS 4
A complete NETCONF protocol data unit (PDU) containing a reply to the <get\-config> operation\&.
.RE
.PP
rpc
.RS 4
A choice of all RPC requests defined in the input YANG modules\&.
.RE
.PP
rpc\-reply
.RS 4
A choice of all RPC replies defined in the input YANG modules\&.
.RE
.PP
notif
.RS 4
A choice of all event notifications defined in the input YANG modules\&.
.RE
.PP
Optional validation of the XML document
\fIinstance\fR
proceeds as follows:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Grammatical and datatype constraints are checked using the RELAX NG schema\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
The DSRL schema is used for adding default values together with ancestor containers to the instance document where necessary\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Semantic constraints are checked using the Schematron schema\&.
.RE
.PP
The script uses programs from the libxml2 suite \-
\fBxsltproc\fR(1) program performs XSLT transformations and
\fBxmllint\fR(1) does RELAX NG validation\&. If necessary, the script could be easily modified for use with other XSLT processors and/or RELAX NG validators\&.
.SH "OPTIONS"
.PP
\fB\-b\fR \fIbasename\fR
.RS 4
Specifies the basename of files in which the output schemas are stored\&. The default is a concatenation of the names of all input YANG modules connected with the underscore character "_"\&.
.RE
.PP
\fB\-d\fR \fIdir\fR
.RS 4
Specifies the directory for output files\&. By default they are stored in the current directory\&.
.RE
.PP
\fB\-h\fR
.RS 4
Displays help screen and exits\&.
.RE
.PP
\fB\-t\fR \fItarget\fR
.RS 4
Specifies the target XML document type using one of the following strings as explained above:
\fBdstore\fR
(default),
\fBget\-reply\fR,
\fBgetconf\-reply\fR,
\fBrpc\fR,
\fBrpc\-reply\fR
or
\fBnotif\fR\&.
.RE
.SH "FILES"
.PP
/usr/local/share/yang/xslt/cts2rng\&.xsl
.RS 4
XSLT stylesheet generating RELAX NG schemas\&.
.RE
.PP
/usr/local/share/yang/xslt/cts2sch\&.xsl
.RS 4
XSLT stylesheet generating Schematron schemas\&.
.RE
.PP
/usr/local/share/yang/xslt/cts2dsrl\&.xsl
.RS 4
XSLT stylesheet generating DSRL schemas\&.
.RE
.PP
/usr/local/share/yang/xslt/gen\-common\&.xsl
.RS 4
Common templates for all three XSLT generators\&.
.RE
.PP
/usr/local/share/yang/schema/relaxng\-lib\&.rng
.RS 4
RELAX NG library of common NETCONF elements\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
\fBPYANG_XSLT_DIR\fR
.RS 4
Alternative directory for XSLT stylesheets\&.
.RE
.PP
\fBPYANG_RNG_LIBDIR\fR
.RS 4
Alternative directory for the RELAX NG library\&.
.RE
.PP
\fBXSLT_OPTS\fR
.RS 4
Options to pass to the XSLT processor\&.
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ yang2dsdl \-v dhcp\&.xml dhcp\&.yang       
    
.fi
.if n \{\
.RE
.\}
.PP
This command generates the DSDL schemas for a datastore contents defined by the
dhcp\&.yang
module and validates an instance document stored in the
dhcp\&.xml
file\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ yang2dsdl \-t rpc rpc\-rock\&.yang
    
.fi
.if n \{\
.RE
.\}
.PP
This command generates the Schematron schema for the input parts (requests) of all RPC operations defined in the module
rpc\-rock\&.yang\&.
.SH "SEE ALSO"
.PP
\fBpyang\fR(1),
\fBxsltproc\fR(1),
\fBxmllint\fR(1)
.PP
The mapping procedure from YANG to DSDL is documented in the Internet Draft draft\-ietf\-netmod\-dsdl\-map\&.
.SH "AUTHORS"
.PP
The
\fByang2dsdl\fR
script and XSLT stylesheets were written by Ladislav Lhotka <lhotka@cesnet\&.cz>\&.
